<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:IGN_25="IGN_25" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" elementFormDefault="qualified" targetNamespace="IGN_25">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://geos.snitcr.go.cr/be/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="caucedrenaje_25kType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="1" name="SHAPE" nillable="false" type="gml:GeometryPropertyType"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="gmlid" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="nom_objeto" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="origen" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="codigo" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="nombre" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="orden" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="longitud" nillable="true" type="xsd:double"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="shape_leng" nillable="true" type="xsd:double"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="caucedrenaje_25k" substitutionGroup="gml:AbstractFeature" type="IGN_25:caucedrenaje_25kType"/>
</xsd:schema>
